micrometer:
  observation:
    http:
      client:
        enabled: true
      server:
        enabled: true

micronaut:
  application:
    name: other
  server:
    port: 8079
  http:
    services:
      users:
        url: http://localhost:8081
      transactions:
        url: http://localhost:8080
  metrics:
    enabled: true
    export:
      otlp:
        enabled: true
        url: http://localhost:4318/v1/metrics

otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317