micrometer:
  observation:
    http:
      client:
        enabled: true
      server:
        enabled: true

micronaut:
  application:
    name: users
  server:
    port: 8081
  metrics:
    enabled: true
    export:
      otlp:
        enabled: true
        url: http://localhost:4318/v1/metrics

otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317