receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

extensions:
  health_check:

  pprof:

  zpages:

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, loki ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, prometheus ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlp ]